# Generated by Django 4.1.7 on 2023-03-30 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='seen_by',
            field=models.ManyToManyField(related_name='seen_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
