# Generated by Django 4.1.7 on 2023-03-30 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation_module', '0001_initial'),
        ('message_module', '0002_messagemodel_seen_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversation_module.conversation'),
        ),
        migrations.AlterField(
            model_name='messagemodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
