# Generated by Django 4.1.7 on 2023-03-30 21:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='C:\\Users\\MHMK\\Desktop\\Code\\Django\\chat_box\\media\\user\\user-default.png', null=True, upload_to='user/')),
                ('last_seen', models.CharField(choices=[('Everyone', 'Everyone'), ('Contacts', 'Contacts'), ('Nobody', 'Nobody')], default='Everyone', max_length=20)),
                ('about_me', models.TextField(blank=True, null=True)),
                ('short_about_me', models.CharField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('do not disturb', 'Do Not Disturb')], default='active', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('see_avatar', models.CharField(choices=[('Everyone', 'Everyone'), ('Contacts', 'Contacts'), ('Nobody', 'Nobody')], default='Everyone', max_length=20)),
                ('see_status', models.CharField(choices=[('Everyone', 'Everyone'), ('Contacts', 'Contacts'), ('Nobody', 'Nobody')], default='Everyone', max_length=20)),
                ('see_channels', models.CharField(choices=[('Everyone', 'Everyone'), ('Contacts', 'Contacts'), ('Nobody', 'Nobody')], default='Everyone', max_length=20)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user/media/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'mp4', 'mkv'])])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='profile_module.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user/attachments/', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx', 'pdf', 'txt', 'xls', 'xlsx', 'zip', 'rar'])])),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='profile_module.userprofile')),
            ],
        ),
    ]
