# Generated by Django 4.1.7 on 2023-03-21 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='C:\\Users\\MHMK\\Desktop\\Code\\Django\\chat_box\\media\\user\\user-default.png', null=True, upload_to='user/')),
                ('last_seen', models.BooleanField(default=False)),
                ('about_user', models.TextField()),
                ('short_about_user', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('away', 'Away'), ('do not disturb', 'Do Not Disturb')], default='active', max_length=20)),
                ('contacts', models.ManyToManyField(blank=True, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
