# Generated by Django 4.1.7 on 2023-03-21 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
