# Generated by Django 4.1.7 on 2023-03-25 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_module', '0003_rename_about_user_userprofile_about_me_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
