# Generated by Django 4.1.7 on 2023-03-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_module', '0004_remove_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='short_about_me',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
