# Generated by Django 4.1.7 on 2023-03-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='C:\\Users\\MHMK\\Desktop\\Code\\Django\\chat_box/media/user/default.png', null=True, upload_to='user'),
        ),
    ]
