# Generated by Django 4.1.7 on 2023-03-20 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_last_seen_user_location_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='short_description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
